#!/usr/bin/env bash
#
# configure-zai.sh — configure Graphiti to use Z.AI (OpenAI-compatible) as the
# LLM, with a masked CLI key prompt. Generates a .env for the Graphiti stack.
#
# Z.AI provides chat/LLM completions (GLM models) but NO embeddings endpoint on
# the global api.z.ai. Graphiti needs both. This script therefore configures:
#   • LLM       → Z.AI  (https://api.z.ai/api/coding/paas/v4, your key)
#   • Embedder  → local sentence-transformers (no key, runs on the box)
#
# Usage:
#   ./scripts/configure-zai.sh
#
# The key is read with read -s (not echoed) and written only to
# /opt/trt-rag/graphiti.env (chmod 600). It is never logged or committed.
#
set -euo pipefail

ZAI_BASE_URL="${ZAI_BASE_URL:-https://api.z.ai/api/coding/paas/v4}"
ZAI_MODEL="${ZAI_MODEL:-glm-4.6}"
ENV_FILE="${ENV_FILE:-/opt/trt-rag/graphiti.env}"

# ── 1. Read the key (masked) ────────────────────────────────────────────────
if [ -t 0 ]; then
  echo "Enter your Z.AI API key (input hidden):"
  read -rs ZAI_KEY
  echo
  if [ -z "$ZAI_KEY" ]; then
    echo "No key entered. Aborting." >&2
    exit 1
  fi
else
  # Allow piping: ZAI_API_KEY=... ./configure-zai.sh
  ZAI_KEY="${ZAI_API_KEY:?Set ZAI_API_KEY or run interactively}"
fi

# Basic shape check (Z.AI keys are a long alphanumeric string). Never print it.
case "$ZAI_KEY" in
  *[!a-zA-Z0-9._-]*)
    echo "Key contains unexpected characters. Check it and retry." >&2
    exit 1
    ;;
esac
echo "Key accepted (length ${#ZAI_KEY}, prefix ${ZAI_KEY:0:4}…)."

# ── 2. Write the Graphiti env file (mode 600, never committed) ──────────────
install -d -m 700 "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by configure-zai.sh — DO NOT COMMIT. chmod 600.
# Z.AI as LLM (OpenAI-compatible); local sentence-transformers for embeddings.

# ── LLM: Z.AI ──────────────────────────────────────────────
OPENAI_API_KEY=${ZAI_KEY}
OPENAI_API_URL=${ZAI_BASE_URL}
MODEL_NAME=${ZAI_MODEL}

# ── Embedder: local (no key) ───────────────────────────────
# Graphiti's openai embedder can't reach Z.AI (no embeddings there), so the
# ingestion script (scripts/ingest_corpus.py) uses sentence-transformers via
# the graphiti-core Python client directly, not the docker MCP embedder.
EMBEDDER_MODEL=sentence-transformers
EOF
chmod 600 "$ENV_FILE"
echo "Wrote ${ENV_FILE} (chmod 600)."

# ── 3. Validate the key against Z.AI (chat/completions, minimal token) ──────
echo "Validating key against ${ZAI_BASE_URL}/chat/completions …"
HTTP_CODE=$(curl -s -o /tmp/zai_check.json -w "%{http_code}" \
  -X POST "${ZAI_BASE_URL}/chat/completions" \
  -H "Authorization: Bearer ${ZAI_KEY}" \
  -H "Content-Type: application/json" \
  -d '{"model":"'"${ZAI_MODEL}"'","messages":[{"role":"user","content":"ping"}],"max_tokens":1}' \
  || true)
if [ "$HTTP_CODE" = "200" ]; then
  echo "✓ Key valid — Z.AI accepted the request (HTTP 200)."
elif [ "$HTTP_CODE" = "404" ]; then
  echo "✗ HTTP 404 — model '${ZAI_MODEL}' not found. Available models:" >&2
  curl -s "${ZAI_BASE_URL}/models" -H "Authorization: Bearer ${ZAI_KEY}" \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print('\n'.join(m['id'] for m in d.get('data',[])))" 2>/dev/null \
    || echo "(could not list models — check the model name in ${ENV_FILE})" >&2
  exit 1
elif [ "$HTTP_CODE" = "401" ] || [ "$HTTP_CODE" = "403" ]; then
  echo "✗ HTTP ${HTTP_CODE} — key rejected. Check the key and the endpoint." >&2
  cat /tmp/zai_check.json >&2 || true
  exit 1
else
  echo "⚠ HTTP ${HTTP_CODE} — endpoint responded but not 200. Body:" >&2
  cat /tmp/zai_check.json >&2 || true
  echo >&2
  echo "The key/env file was still written; investigate and re-run if needed." >&2
fi
rm -f /tmp/zai_check.json

# ── 4. Wire the env into the docker stack ───────────────────────────────────
COMPOSE=/opt/trt-rag/graphiti/mcp_server/docker/docker-compose-falkordb-safe.yml
if [ -f "$COMPOSE" ]; then
  # Point the MCP container at the generated env file + Z.AI base URL
  python3 - "$COMPOSE" "$ENV_FILE" <<'PY'
import sys, re
path, env = sys.argv[1], sys.argv[2]
s = open(path).read()
# ensure env_file references the generated env
if 'graphiti.env' not in s:
    s = s.replace('    image: zepai/knowledge-graph-mcp:standalone',
                  '    image: zepai/knowledge-graph-mcp:standalone\n    env_file: ' + env)
# set Z.AI base URL + model on the service env
for key, val in [('OPENAI_API_URL', 'https://api.z.ai/api/coding/paas/v4'),
                 ('MODEL_NAME', 'glm-4.6')]:
    pat = re.compile(r'      - ' + key + r'=.*\n')
    if pat.search(s):
        s = pat.sub('      - ' + key + '=' + val + '\n', s)
    elif '      - TELEMETRY_ENABLED=false' in s:
        s = s.replace('      - TELEMETRY_ENABLED=false',
                      '      - TELEMETRY_ENABLED=false\n      - ' + key + '=' + val)
open(path, 'w').write(s)
print(f'Updated {path} (env_file + Z.AI config).')
PY
  echo "Restart the stack to apply:"
  echo "  docker compose -f $COMPOSE down && docker compose -f $COMPOSE up -d"
else
  echo "Compose file not found at $COMPOSE — skipping docker wiring."
fi

echo
echo "Done. To BUILD the graph (the one LLM-dependent step):"
echo "  cd /opt/trt && python3 scripts/ingest_corpus.py"
